apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: production
  namespace: argocd
  labels:
    environment: prod
spec:
  project: prod
  source:
    repoURL: https://github.com/noordlabs/data-platform-v1
    targetRevision: refs/heads/main
    path: platform/argo/argo-spec/apps/
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 20
      backoff:
        duration: 10s
        factor: 2